### ISSUE TITLE
Vetur: Syntax highlighting not correct in some cases

### ISSUE THREAD

**Issue by Towerism** [onivim/oni2#1174]
I Installed vetur vscode extension which I use when I am editing vue single file components. I get an error when opening up a .vue file.

> Request initialize failed with message: Cannot read property 'suggest' of undefined.

The extension does not really function other than syntax highlighting.

**Comment by Towerism** [comment]
Just tested vetur again today. This specific error is gone. @bryphe are you comfortable with me closing this issue?

**Comment by haringsrob** [comment]
I tried it today (nightly build), not much seems to happen..

**Comment by rraihansaputra** [comment]
I can't install `octref.vetur-0.24.0.vsix` through `oni2 --install-extension path.vsix`. Pulled and build from commit 93dc2d58

**Comment by pkariz** [comment]
to me it installs it, but i have pretty much no syntax highlight (2 lines out of 200). `gd` in the typescript part seems to be working well

**Comment by bryphe** [comment]
I just tried this out as well - seems to be working:
![image](https://user-images.githubusercontent.com/13532591/88003142-04696d00-cab9-11ea-9db8-7dd890611927.png)

Using this `vsix` here: https://github.com/vuejs/vetur/releases/download/v0.24.0/vetur-0.24.0.vsix

> to me it installs it, but i have pretty much no syntax highlight (2 lines out of 200). gd in the typescript part seems to be working well

@pkariz - is the file you used open-source? And which theme are you using? Would like to check it out

**Comment by bryphe** [comment]
The root issue:

> Request initialize failed with message: Cannot read property 'suggest' of undefined.

Was fixed in this PR: #1967

**Comment by pkariz** [comment]
still a problem. It seems like some (not all!) inline stuff is making problems, eg:
```vue
<template>
  <v-flex xs12>
    <v-progress-linear v-if="loading" height="5" indeterminate></v-progress-linear>
  </v-flex>
</template>

<script lang="ts">
import axios from 'axios';
import { Component, Prop, Vue } from 'vue-property-decorator';

@Component
export default class App extends Vue {
  public title = 'Bla';

  public hello() {
    console.log('bla');
  }

  public bla = 1;
}
</script>

<style lang="sass" scoped>
.bounce-leave-active 
  animation: bounce-in .2s reverse
  transition: opacity .2s

@keyframes bounce-in 
  0% 
    transform: scale(0.92)
  100% 
    transform: scale(1)
</style>
```
if you put `</v-progress-linear>` in a new line, it highlights correctly the template part, but function hello is all the same color (don't know why and if that's wrong or not). Also sass is not highlighted, not sure if that's ok or not

**Comment by tofulm** [comment]
I just tested today with the last build (407c09b0) , it's ok for me !!

**Comment by kakamorsch** [comment]
@bryphe I think that you can close this issue, since the Vetur is working now.

**Comment by mabasic** [comment]
Vetur incorrectly highlights code for me. Tried it just now with `oni2 0.5.9 nightly 22e5bf42` and `vetur 0.31.3`. First two lines in a .vue file are almost correctly highlighted, the rest is garbage.
