### ISSUE TITLE
Add syntax highlighting to hover popup

### ISSUE THREAD

**Issue by yunti** [onivim/oni2#1947]
Thanks for the recent addition of hover info and the `gh` shortcut too which is great, and makes a huge difference to the experience in onivim2

Perhaps it's already on your next steps, but it would be great to have syntax highlighting in the hover info.

Below is a comparison versus vscode. 
Which shows what a difference highlighting makes.
(Additionally onivim seem to have a larger font used for the file location which appears in the popup, giving it the emphasis. Rather than the type info.
Vscode doesn't show this (or do I have it turned off?) which makes the hover info more focused and the current file used is probably obvious so doesn't seem to add much here).

vscode:
<img width="388" alt="image" src="https://user-images.githubusercontent.com/1826271/84901667-b7523f80-b0a3-11ea-9573-c5f07ea695c7.png">
Onivim:
<img width="349" alt="image" src="https://user-images.githubusercontent.com/1826271/84902052-347db480-b0a4-11ea-99c2-5cd7e1e8b7ce.png">

**Comment by bryphe** [comment]
Hi @yunti ,

> Thanks for the recent addition of hover info and the gh shortcut too which is great, and makes a huge difference to the experience in onivim2

Great to hear!

Thanks for logging the issue. Seems like there are two issues:

1) We're showing the file location, which probably doesn't need to be there
2) No syntax highlighting

For the first issue - I need to check, but we may be handling the setting for `show_module_path_on_hover` incorrectly:
https://github.com/jaredly/reason-language-server/blob/f523b11e63c19dce25b8ceae895ad28ffcb085b6/src/lsp/NotificationHandlers.re#L111

For the second issue - it seems that, when there is an anonymous code-block in the markdown, like:
```
     ["'''\n(\n  ~children: 'children,\n  ~key: option(string),\n  unit\n) => Js.t(< children : 'children >)\n''';''
       ];
```

We aren't handling it quite correctly - we should be falling back to the filetype of the active editor, but I think we're just falling back to plaintext now.

**Comment by bryphe** [comment]
#1954 fixes the first issue

@zbaylin , is there a convenient to set a 'default' filetype for the markdown renderer? If so - we should set the default (no language specified) to the filetype of the active buffer. I believe that would address the second issue, that there is no syntax highlighting applied.

**Comment by zbaylin** [comment]
That's a good question. Right now there isn't but it's definitely something I can add in the Markdown component here. It shouldn't be too hard, I can look into it tonight!

**Comment by bryphe** [comment]
Cool, thanks for the help @zbaylin !

**Comment by zbaylin** [comment]
Fixed :)
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/4527949/84968890-8561cd00-b0e5-11ea-8704-93125256b571.png">

Will make a PR shortly

**Comment by yunti** [comment]
Amazing, thanks for improving this so quickly!

**Comment by bryphe** [comment]
Looks like this should be fixed now with #1954 and #1955

**Comment by yunti** [comment]
Just tried out with the latest nightly build. Thanks for merging the fixes. But I'm still getting hover without syntax highlighting. The #4011c83a looks to be in the nightly build so looks like it should have been picked up.
(Aside: it looks like your font size for hover is too small too. I think the vscode editor and hover font size looks to be the same at 14px. Oni2 default font size looks to be ~16px but the hover looks around 10px making it probably a bit too small).
Screenshots to clarify.

oni2
<img width="470" alt="image" src="https://user-images.githubusercontent.com/1826271/85141810-434c9e80-b23f-11ea-934a-80273c5e8a0c.png">
<img width="220" alt="image" src="https://user-images.githubusercontent.com/1826271/85141836-4fd0f700-b23f-11ea-9fe1-959e049ae08c.png">


vscode:
<img width="436" alt="image" src="https://user-images.githubusercontent.com/1826271/85141890-670fe480-b23f-11ea-9ee8-f80c530cabab.png">
<img width="362" alt="image" src="https://user-images.githubusercontent.com/1826271/85142027-a8a08f80-b23f-11ea-8fb4-7a9fa2be5272.png">

**Comment by yunti** [comment]
This may be a separate issue. But the type info on completion is also missing highlighting.

<img width="589" alt="image" src="https://user-images.githubusercontent.com/1826271/85142242-f5846600-b23f-11ea-856b-79f38473586c.png">

**Comment by bryphe** [comment]
> (Aside: it looks like your font size for hover is too small too. I think the vscode editor and hover font size looks to be the same at 14px. Oni2 default font size looks to be ~16px but the hover looks around 10px making it probably a bit too small).

Good call, I think we should use the same size for the editor + hover - does that seem OK to you @zbaylin ?

Wondering if the syntax highlighting issue is related to #1974 - I noticed this with `ocaml-lsp` too

**Comment by zbaylin** [comment]
@yunti are you able to run Oni with the flags `--trace --log-filter Revery.Components.Markdown` and post what logs you get on hover? You should see an S-Expression of the parsed markdown, which will help me determine where in the chain the syntax highlighting is failing.

Thanks!

**Comment by yunti** [comment]
@zbaylin that didn't produce any output unfortunately. `oni2 . --trace --log-filter Revery.Components.Markdown`. I'm using the nightly builds rather than building from source. Would that prevent showing output?

**Comment by zbaylin** [comment]
Ah my bad, you also have to include `-f` to prevent forking. The final command should be `oni2 . -f --trace --log-filter Revery.Components.Markdown`

**Comment by yunti** [comment]
@zbaylin. I haven't had a moment to look through the output, but hopefully it has the necessary details. Thanks. 

https://gist.github.com/yunti/135e8d847ca9ad8c4428ec7ba60ed531

**Comment by zbaylin** [comment]
Very helpful, thanks @yunti!

**Comment by zbaylin** [comment]
![image](https://user-images.githubusercontent.com/4527949/85339933-1bfe0780-b4b3-11ea-8e80-267dfdabd1eb.png)
Fixed for real this time 😅.

Sorry about that last time! I thought I had tested it correctly but I guess I hadn't. I was able to repro what you got just with the ReasonReact example project.

Will make a PR shortly!
