### ISSUE TITLE
cmd + p crashing app

### ISSUE THREAD

**Issue by zacharymacke** [onivim/oni2#540]
On a fresh install first time open, cmd + p bringing up the file explorer crashes the application. Sometimes it will stay open fine but crashes upon typing first letter. OSX 10.14.5

**Comment by nolondil** [comment]
As I have experienced it too: it seems it tries to list too many items or one item is forbidden for Oni2. When I launch Oni2 directly in a directory (through the terminal) I don't run into any issue with cmd + p.

**Comment by zacharymacke** [comment]
I will try and run through terminal and see if that fixes it!

**Comment by nolondil** [comment]
(JIC) I give the path of the project folder as an argument to the oni2 command.

**Comment by CrossR** [comment]
>As I have experienced it too: it seems it tries to list too many items or one item is forbidden for Oni2. When I launch Oni2 directly in a directory (through the terminal) I don't run into any issue with cmd + p.

I expect this is the case, since MacOS is pretty protective over certain folders, so it wouldn't suprirse me if we run ripgrep over some places we shouldn't and hit some issues.

**Comment by anisjonischkeit** [comment]
Looks like the same issue as #467

**Comment by bryphe** [comment]
This should be fixed now on OSX with #467

**Comment by jpinnix** [comment]
I am still experiencing this with the last several nightly builds.

**Comment by bryphe** [comment]
Thanks for the heads up, @jpinnix - will take a look.

**Comment by bryphe** [comment]
This should be fixed now (no longer crashes in large directories). 

The main fix for this was in #693 - which time-slices our processing of the results, so that we can stay on top of processing output from Ripgrep.

There are still improvements we can make to improve the speed of processing (important for large directories) - but the crash should no longer reproduce. I'll close this, but please let me know if you're still seeing crashes with Ripgrep on latest builds 👍

**Comment by raguay** [comment]
01/21/2020

macOS 10.15.2
Oni2 just built on 01/21/2020

## Actions taken

1) <cmd>+P, while the files are listing type the name of one of them and press enter.

## What should happen

It should open a buffer in that file

## What happened

Total crash of Oni2 with a crash log of:
```
Fontkit.FontKitRenderGlyphException("[ERROR]: Unable to render character at FT_Load_Char\n"):
```

Not sure if it’s related to this issue, but this one seemed to be the closest match.

**Comment by bryphe** [comment]
I believe this particular issue should be fixed now - this code-path: 
```
Fontkit.FontKitRenderGlyphException("[ERROR]: Unable to render character at FT_Load_Char\n"):
```
is no longer code we run since switching to Skia. So hopefully this is fixed! But please feel free to open a new issue if this is still being hit.
