### ISSUE TITLE
Proper handling of path completion

### ISSUE THREAD

**Issue by yunti** [onivim/oni2#754]
Currently path completion, to eg a folder, isn't handled properly like vim.

When typing a path name `/` is not added after each directory which means this much be manually inserted each time.

(additionally as mentioned by manuhornung,  there are errors when there are spaces in the path).

**Comment by yunti** [comment]
This appears to work correctly now possibly fixed by the recent autocompletion work? #2202 
@bryphe 
<img width="262" alt="image" src="https://user-images.githubusercontent.com/1826271/89530599-b0fc5c00-d7e6-11ea-94a1-bd5200bb93ac.png">

**Comment by bryphe** [comment]
Awesome, thanks @yunti !

Ya, there is one more case I'm tracking here: https://github.com/onivim/oni2/issues/434 - but glad we can close this one out 👍

**Comment by delkano** [comment]
This should not be closed. Even on the screenshot there you can see there is no trailing slash after "/reason". I tested on today's AppImage and it still doesn't work correctly.
