### ISSUE TITLE
Display gets crazy after left clicking preview and moving mouse.

### ISSUE THREAD

**Issue by m-kru** [onivim/oni2#817]
![preview](https://user-images.githubusercontent.com/26227737/66254461-c2b04580-e776-11e9-9af9-8f3be630a044.png)

When I left click on preview and move mouse weird thing happens. With each mouse move the document is scrolling, even if I release left mouse button.
It does not stop if I left click in some different area.
Ok, it stops when I left click in preview again. Is it desirable behavior?

**Comment by bryphe** [comment]
Thanks for logging this, @m-kru ! Definitely a bug 👍

**Comment by bryphe** [comment]
Should be fixed now with #819

**Comment by m-kru** [comment]
It is much better, however this buggy behavior still occurs, but is much rare. Like once per 20-30 times.
